version: '3.8'
services:
  movies:
    image: sairam261093/paytmmoviesrepo:latest
    ports:
      - "81:80"
    deploy:
      replicas: 3
  train:
    image: sairam261093/paytmtrainrepo:latest
    ports:
      - "82:80"
    deploy:
      replicas: 3
  dth:
    image: sairam261093/paytmdthrepo:latest
    ports:
      - "83:80"
    deploy:
      replicas: 3
  recharge:
    image: sairam261093/paytmrechargerepo:latest
    ports:
      - "84:80"
    deploy:
      replicas: 3

